# Generated by Django 5.2.17 on 2026-09-29 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('min_redemption_amount', models.DecimalField(decimal_places=2, default=100, max_digits=12)),
                ('max_redemption_amount', models.DecimalField(decimal_places=2, default=50000, max_digits=12)),
                ('coupon_expiry_days', models.IntegerField(default=365)),
                ('allow_partial_redemption', models.BooleanField(default=True)),
                ('allow_combined_offers', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(default='USER', max_length=50)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AlterModelOptions(
            name='datastore',
            options={},
        ),
        migrations.AlterModelTable(
            name='datastore',
            table='core_datastore',
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('pnr', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('passenger_name', models.CharField(max_length=150)),
                ('passenger_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('travel_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('booked_date', models.DateField(blank=True, null=True)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('airline_pnr', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='Confirmed', max_length=30)),
                ('booking_type', models.CharField(default='Web Booking', max_length=50)),
                ('travel_type', models.CharField(default='One Way', max_length=50)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('office_id', models.CharField(blank=True, max_length=50, null=True)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('airline', models.CharField(blank=True, max_length=100, null=True)),
                ('fare_type', models.CharField(default='Net Fare', max_length=50)),
                ('parent_pnr', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.customer')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='PENDING', max_length=30)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, db_column='booking_ref', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='core.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='core.customer')),
            ],
            options={
                'db_table': 'ledger',
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='SUCCESS', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='core.customer')),
            ],
            options={
                'db_table': 'redemptions',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('office_id', models.CharField(blank=True, max_length=50, null=True)),
                ('booking_type', models.CharField(default='Any Booking Type', max_length=50)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('airline', models.CharField(blank=True, max_length=100, null=True)),
                ('fare_type', models.CharField(default='Any Fare Type', max_length=50)),
                ('percentage', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rules',
                'indexes': [models.Index(fields=['status'], name='rules_status_112926_idx'), models.Index(fields=['airline'], name='rules_airline_63798c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('passenger_name', models.CharField(blank=True, max_length=150, null=True)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AVAILABLE', 'Available'), ('REDEEMED', 'Redeemed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('available_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('redeemed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(db_column='booking_ref', on_delete=django.db.models.deletion.PROTECT, related_name='coupon', to='core.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='core.customer')),
            ],
            options={
                'db_table': 'coupons',
                'indexes': [models.Index(fields=['customer'], name='coupons_custome_32d3da_idx'), models.Index(fields=['status'], name='coupons_status_9a69d0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client'], name='bookings_client__70b0b6_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['travel_date'], name='bookings_travel__9ec806_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['passenger_name'], name='bookings_passeng_711a77_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['airline'], name='bookings_airline_c535e4_idx'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['customer'], name='ledger_custome_2ded5e_idx'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['date'], name='ledger_date_d59614_idx'),
        ),
        migrations.AddIndex(
            model_name='redemption',
            index=models.Index(fields=['customer'], name='redemptions_custome_20c00a_idx'),
        ),
        migrations.AddIndex(
            model_name='redemption',
            index=models.Index(fields=['status'], name='redemptions_status_f4f431_idx'),
        ),
    ]
