# Generated by Django 5.2.17 on 2026-09-29 09:19

import django.db.models.deletion
from django.db import migrations, models


def create_redemption_allocations_if_missing(apps, schema_editor):
    RedemptionAllocation = apps.get_model("core", "RedemptionAllocation")
    table_name = RedemptionAllocation._meta.db_table
    if table_name not in schema_editor.connection.introspection.table_names():
        schema_editor.create_model(RedemptionAllocation)


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0003_customer_setting_user_alter_datastore_options_and_more",
        ),
    ]

    operations = [

        # =========================================================
        # REDEMPTION ALLOCATION
        # Keep the legacy table shape in migration state, and create the
        # physical table only when a fresh database does not have it.
        # =========================================================
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="RedemptionAllocation",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "coupon_code",
                            models.CharField(max_length=100),
                        ),
                        (
                            "amount",
                            models.DecimalField(
                                decimal_places=2,
                                default=0,
                                max_digits=12,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "redemption_allocations",
                    },
                ),
            ],
        ),

        migrations.RunPython(
            create_redemption_allocations_if_missing,
            migrations.RunPython.noop,
        ),

        # =========================================================
        # DATASTORE
        # core_datastore is already deleted.
        #
        # So delete only from Django STATE.
        # Do NOT try to DROP the table again.
        # =========================================================
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name="DataStore",
                ),
            ],
        ),

        # =========================================================
        # COUPON
        # booking_ref already exists
        # =========================================================

        migrations.AddField(
            model_name="coupon",
            name="coupon_code",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="coupon",
            name="customer_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="coupon",
            name="unlock_date",
            field=models.DateField(
                blank=True,
                null=True,
            ),
        ),

        # =========================================================
        # CUSTOMER
        # =========================================================

        migrations.AddField(
            model_name="customer",
            name="passenger_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
            ),
        ),

        # =========================================================
        # LEDGER
        # booking_ref already exists
        # =========================================================

        migrations.AddField(
            model_name="ledger",
            name="coupon_code",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="ledger",
            name="customer_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="ledger",
            name="txn_id",
            field=models.CharField(
                blank=True,
                max_length=60,
                null=True,
                unique=True,
            ),
        ),

        # =========================================================
        # REDEMPTION
        # =========================================================

        migrations.AddField(
            model_name="redemption",
            name="booking_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="redemption",
            name="booking_ref",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="redemption",
            name="coupon_code",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="redemption",
            name="customer_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="redemption",
            name="redeemed_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
            ),
        ),

        migrations.AddField(
            model_name="redemption",
            name="redemption_type",
            field=models.CharField(
                default="Coupon Redemption",
                max_length=50,
            ),
        ),

        migrations.AddField(
            model_name="redemption",
            name="reversed_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
            ),
        ),

        migrations.AddField(
            model_name="redemption",
            name="reversed_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="redemption",
            name="time",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
            ),
        ),

        # =========================================================
        # BOOKING
        # =========================================================

        migrations.AlterField(
            model_name="booking",
            name="travel_date",
            field=models.DateField(
                blank=True,
                null=True,
            ),
        ),

        # =========================================================
        # COUPON BOOKING FK
        # =========================================================

        migrations.AlterField(
            model_name="coupon",
            name="booking",
            field=models.OneToOneField(
                blank=True,
                db_column="booking_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coupon",
                to="core.booking",
            ),
        ),

        # =========================================================
        # LEDGER BOOKING FK
        # =========================================================

        migrations.AlterField(
            model_name="ledger",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                db_column="booking_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_entries",
                to="core.booking",
            ),
        ),

        # =========================================================
        # LEDGER CUSTOMER FK
        # =========================================================

        migrations.AlterField(
            model_name="ledger",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_entries",
                to="core.customer",
            ),
        ),

        # =========================================================
        # REDEMPTION CUSTOMER FK
        # =========================================================

        migrations.AlterField(
            model_name="redemption",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="redemptions",
                to="core.customer",
            ),
        ),

        # =========================================================
        # REDEMPTION STATUS
        # =========================================================

        migrations.AlterField(
            model_name="redemption",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                    ("PENDING", "Pending"),
                    ("COMPLETED", "Completed"),
                    ("REVERSED", "Reversed"),
                ],
                default="SUCCESS",
                max_length=20,
            ),
        ),

        # =========================================================
        # REDEMPTION ALLOCATION -> REDEMPTION FK
        # Existing table already has id, coupon_code, amount.
        # This will add redemption_id.
        # =========================================================

        migrations.AddField(
            model_name="redemptionallocation",
            name="redemption",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocations",
                to="core.redemption",
            ),
        ),
    ]