# Generated by Django 5.2.17 on 2026-09-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_redemptionallocation_delete_datastore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='booking_ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='booking_ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
