# Generated by Django 5.2.17 on 2026-10-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_swap_business_premium_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='flat_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
