# Generated by Django 5.2.17 on 2026-10-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_passenger_id_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
