# Generated by Django 5.2.17 on 2026-10-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_populate_ticket_no'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "ALTER TABLE coupons DROP FOREIGN KEY coupons_booking_fk",
                "ALTER TABLE ledger DROP FOREIGN KEY ledger_booking_fk",
                (
                    "ALTER TABLE bookings "
                    "ADD COLUMN id BIGINT NOT NULL AUTO_INCREMENT, "
                    "ADD UNIQUE KEY booking_id_unique (id)"
                ),
                (
                    "UPDATE coupons c JOIN bookings b ON b.pnr = c.booking_id "
                    "SET c.booking_id = b.id"
                ),
                (
                    "UPDATE ledger l JOIN bookings b ON b.pnr = l.booking_id "
                    "SET l.booking_id = b.id"
                ),
                (
                    "UPDATE redemptions r JOIN bookings b ON b.pnr = r.booking_id "
                    "SET r.booking_id = CAST(b.id AS CHAR)"
                ),
                "ALTER TABLE coupons MODIFY booking_id BIGINT NULL",
                "ALTER TABLE ledger MODIFY booking_id BIGINT NULL",
                (
                    "ALTER TABLE bookings DROP PRIMARY KEY, "
                    "DROP INDEX booking_id_unique, "
                    "ADD PRIMARY KEY (id), "
                    "ADD KEY bookings_pnr_idx (pnr)"
                ),
                (
                    "ALTER TABLE coupons ADD CONSTRAINT coupons_booking_fk "
                    "FOREIGN KEY (booking_id) REFERENCES bookings (id) "
                    "ON DELETE SET NULL"
                ),
                (
                    "ALTER TABLE ledger ADD CONSTRAINT ledger_booking_fk "
                    "FOREIGN KEY (booking_id) REFERENCES bookings (id) "
                    "ON DELETE SET NULL"
                ),
            ],
            reverse_sql=None,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="booking",
                    name="id",
                    field=models.BigAutoField(primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name="booking",
                    name="pnr",
                    field=models.CharField(max_length=50),
                ),
            ],
        ),
    ]
