# Generated by Django 5.2.17 on 2026-10-08 07:55

from django.db import migrations, models


def migrate_booking_primary_key(apps, schema_editor):
    connection = schema_editor.connection
    quote = connection.ops.quote_name
    required_columns = {
        "bookings": {"pnr"},
        "coupons": {"booking_id"},
        "ledger": {"booking_id"},
        "redemptions": {"booking_id"},
    }

    with connection.cursor() as cursor:
        for table, required in required_columns.items():
            columns = {
                column.name
                for column in connection.introspection.get_table_description(cursor, table)
            }
            missing = required - columns
            if missing:
                raise RuntimeError(
                    f"Cannot migrate booking IDs: {table} is missing "
                    f"{', '.join(sorted(missing))}."
                )

        for table in ("coupons", "ledger"):
            constraints = connection.introspection.get_constraints(cursor, table)
            for name, constraint in constraints.items():
                foreign_key = constraint.get("foreign_key")
                if (
                    constraint.get("columns") == ["booking_id"]
                    and foreign_key
                    and foreign_key[0] == "bookings"
                ):
                    cursor.execute(
                        f"ALTER TABLE {quote(table)} "
                        f"DROP FOREIGN KEY {quote(name)}"
                    )

        booking_columns = {
            column.name
            for column in connection.introspection.get_table_description(cursor, "bookings")
        }
        if "id" not in booking_columns:
            cursor.execute(
                f"ALTER TABLE {quote('bookings')} "
                f"ADD COLUMN {quote('id')} BIGINT NULL"
            )
            cursor.execute(f"SELECT {quote('pnr')} FROM {quote('bookings')} WHERE {quote('id')} IS NULL")
            import uuid
            for (pnr_val,) in cursor.fetchall():
                gen_id = uuid.uuid4().int & ((1 << 63) - 1)
                cursor.execute(
                    f"UPDATE {quote('bookings')} SET {quote('id')} = %s WHERE {quote('pnr')} = %s AND {quote('id')} IS NULL",
                    [gen_id, pnr_val],
                )
            cursor.execute(
                f"ALTER TABLE {quote('bookings')} "
                f"MODIFY {quote('id')} BIGINT NOT NULL"
            )

        cursor.execute(
            "UPDATE coupons c JOIN bookings b ON b.pnr = c.booking_id "
            "SET c.booking_id = b.id"
        )
        cursor.execute(
            "UPDATE ledger l JOIN bookings b ON b.pnr = l.booking_id "
            "SET l.booking_id = b.id"
        )
        cursor.execute(
            "UPDATE redemptions r JOIN bookings b ON b.pnr = r.booking_id "
            "SET r.booking_id = CAST(b.id AS CHAR)"
        )
        cursor.execute(
            f"ALTER TABLE {quote('coupons')} "
            f"MODIFY {quote('booking_id')} BIGINT NULL"
        )
        cursor.execute(
            f"ALTER TABLE {quote('ledger')} "
            f"MODIFY {quote('booking_id')} BIGINT NULL"
        )

        constraints = connection.introspection.get_constraints(cursor, "bookings")
        primary_key = next(
            (
                constraint
                for constraint in constraints.values()
                if constraint.get("primary_key")
            ),
            None,
        )
        if not primary_key or primary_key.get("columns") != ["id"]:
            if primary_key:
                cursor.execute(f"ALTER TABLE {quote('bookings')} DROP PRIMARY KEY")
            cursor.execute(f"ALTER TABLE {quote('bookings')} ADD PRIMARY KEY ({quote('id')})")

        constraints = connection.introspection.get_constraints(cursor, "bookings")
        if "booking_id_unique" in constraints:
            cursor.execute(
                f"ALTER TABLE {quote('bookings')} "
                f"DROP INDEX {quote('booking_id_unique')}"
            )

        constraints = connection.introspection.get_constraints(cursor, "bookings")
        has_pnr_index = any(
            constraint.get("columns") == ["pnr"]
            for constraint in constraints.values()
        )
        if not has_pnr_index:
            cursor.execute(
                f"ALTER TABLE {quote('bookings')} "
                f"ADD KEY {quote('bookings_pnr_idx')} ({quote('pnr')})"
            )

        for table in ("coupons", "ledger"):
            constraints = connection.introspection.get_constraints(cursor, table)
            has_booking_fk = any(
                constraint.get("columns") == ["booking_id"]
                and constraint.get("foreign_key") == ("bookings", "id")
                for constraint in constraints.values()
            )
            if not has_booking_fk:
                cursor.execute(
                    f"ALTER TABLE {quote(table)} "
                    f"ADD CONSTRAINT {quote(f'{table}_booking_fk')} "
                    f"FOREIGN KEY ({quote('booking_id')}) "
                    f"REFERENCES {quote('bookings')} ({quote('id')}) "
                    "ON DELETE SET NULL"
                )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_populate_ticket_no'),
    ]

    operations = [
        migrations.RunPython(
            migrate_booking_primary_key,
            migrations.RunPython.noop,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="booking",
                    name="id",
                    field=models.BigAutoField(primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name="booking",
                    name="pnr",
                    field=models.CharField(max_length=50),
                ),
            ],
        ),
    ]
