# Generated by Django 5.2.17 on 2026-10-08 12:48

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_complete_fresh_database_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.BigIntegerField(default=core.models.generate_booking_id, primary_key=True, serialize=False),
        ),
    ]
