from django.urls import path
from core import views

urlpatterns = [
    path("", views.login_view, name="login"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("client-portal/", views.client_portal, name="client_portal"),
    path("customers/", views.customers, name="customers"),
    path("customers/add/", views.add_customer, name="add_customer"),
    path("customers/edit/", views.edit_customer, name="edit_customer"),
    path("customers/delete/", views.delete_customer, name="delete_customer"),
    path("bookings/", views.bookings, name="bookings"),
    path("bookings/add/", views.add_booking, name="add_booking"),
    path("bookings/edit/", views.edit_booking, name="edit_booking"),
    path("bookings/delete/", views.delete_booking, name="delete_booking"),
    path("coupons/", views.coupons, name="coupons"),
    path("coupons/earn/", views.earn_coupon, name="earn_coupon"),
    path("coupons/release/", views.release_coupon, name="release_coupon"),
    path("coupons/redeem/", views.redeem_coupon, name="redeem_coupon"),
    path("coupons/reverse/", views.reverse_coupon, name="reverse_coupon"),
    path("redemptions/", views.redemptions, name="redemptions"),
    path("redemptions/add/", views.add_redemption, name="add_redemption"),
    path("redemptions/delete/", views.delete_redemption, name="delete_redemption"),
    path("redemptions/clear-all/", views.clear_all_redemptions, name="clear_all_redemptions"),
    path("ledger/", views.ledger, name="ledger"),
    path("excel-upload/", views.excel_upload, name="excel_upload"),
    path("rules/", views.rules, name="rules"),
    path("rules/add/", views.add_rule, name="add_rule"),
    path("rules/delete/", views.delete_rule, name="delete_rule"),
    path("settings/", views.settings_page, name="settings"),
    path("settings/save/", views.save_settings, name="save_settings"),
]
